// <auto-generated />
namespace AdminWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixedCityHotelConnection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedCityHotelConnection));
        
        string IMigrationMetadata.Id
        {
            get { return "201710071343491_Fixed City Hotel Connection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
